### ISSUE TITLE
GDLJS bones

### ISSUE THREAD

**Issue by sirgalleto** [gdljs/gdljs.github.io#1]
Sólo una página diciendo GDLJS con fondo amarillo. 

Mock: 
![Screen Shot 2020-04-15 at 9 49 35 PM](https://user-images.githubusercontent.com/5873627/79409230-045e4c00-7f63-11ea-8fc9-10be9266c00d.png)

**Comment by carlosangon** [comment]
@arathjz @sirgalleto 

Here is a zip file with 2 versions of the logo. PNG with transparent bg and SVG if needed.

[GDLjs_logo.zip](https://github.com/gdljs/gdljs.github.io/files/4493881/GDLjs_logo.zip)

**Comment by carlosangon** [comment]
Also here is some sample of "yellow" from the google material color palette
![Screen Shot 2020-04-17 at 11 01 59 AM](https://user-images.githubusercontent.com/2627624/79589417-fa3f6900-809a-11ea-825b-d813bf82493a.png)
.

**Comment by arathjz** [comment]
@carlosangon thanks. @sirgalleto what's the name of the typography?
