### ISSUE TITLE
Add GDLJS Social media

### ISSUE THREAD

**Issue by arathjz** [gdljs/gdljs.github.io#6]
Twitter: https://twitter.com/gdl_js
Github: https://github.com/gdljs
Slack http://slack.gdljs.com/
Facebook: https://www.facebook.com/gdljs/
Instagram: https://www.instagram.com/gdl_js/
Twitch: https://www.twitch.tv/gdljs
Meetup: https://www.meetup.com/Guadalajara-JS/

**Comment by carlosangon** [comment]
I'd say use a service like FontAwesome or Material icons for this, but open to suggestions.
